#version: '3.8'
#
#services:
#  discovery-server:
#    build:
#      context: ./discovery-server
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    networks:
#      - backend-network
#
#  config-server:
#    build:
#      context: ./config-server
#    container_name: config-server
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./config-repo:/config-repo  # your config files mounted here
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config-repo
#    depends_on:
#      - discovery-server
#    networks:
#      - backend-network
#
#  auth-service:
#    build:
#      context: ./auth-service
#    container_name: auth-service
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#    depends_on:
#      - discovery-server
#      - config-server
#    networks:
#      - backend-network
#
#  student-service:
#    build:
#      context: ./student-service
#    container_name: student-service
#    ports:
#      - "8082:8082"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#    depends_on:
#      - discovery-server
#      - config-server
#    networks:
#      - backend-network
#
#  api-gateway:
#    build:
#      context: ./api-gateway
#    container_name: api-gateway
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#    depends_on:
#      - discovery-server
#      - config-server
#      - auth-service
#      - student-service
#    networks:
#      - backend-network
#
#networks:
#  backend-network:
#    driver: bridge
