  spring:
    application:
      name: config-server
    cloud:
      config:
              server:
                git:
                  uri: https://github.com/Omkar-Ugal/config-repo
                  clone-on-start: true

  server:
     port: 8888

  application:
    name: config-server

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/